# Generated by Django 3.2.3 on 2021-09-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('ESTANDAR', 'Estandar'), ('PREMIUM', 'Premium'), ('VIP', 'Vip')], default='ESTANDAR', max_length=150)),
                ('capacidad', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='numMaximoPersonas',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
