# Generated by Django 3.2.3 on 2021-09-03 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0002_auto_20210903_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitaciones',
            name='nombre',
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hoteles', to='hoteles.hotel'),
        ),
    ]
