# Generated by Django 3.2.3 on 2021-09-03 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0003_auto_20210903_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitaciones',
            name='descripcion',
        ),
    ]
